// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBOgcphDfB_pbEKLZTsjfB2RiNeR51Rc',
    appId: '1:1047355236192:web:8550576f00d975847fc805',
    messagingSenderId: '1047355236192',
    projectId: 'we-chat-a3450',
    authDomain: 'we-chat-a3450.firebaseapp.com',
    storageBucket: 'we-chat-a3450.appspot.com',
    measurementId: 'G-7NSZS787CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0yerXNEuMEFMnoS-7vkL42Y2az5-83A4',
    appId: '1:1047355236192:android:99f9515212a997e17fc805',
    messagingSenderId: '1047355236192',
    projectId: 'we-chat-a3450',
    storageBucket: 'we-chat-a3450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZEm9ceSJy87Urljo0jLbjo51kt5wBNn4',
    appId: '1:1047355236192:ios:c80a83f83ba03f3a7fc805',
    messagingSenderId: '1047355236192',
    projectId: 'we-chat-a3450',
    storageBucket: 'we-chat-a3450.appspot.com',
    androidClientId: '1047355236192-sotl8situia81g3ribv9feugl6tn0b1h.apps.googleusercontent.com',
    iosClientId: '1047355236192-87rb0l8034n6hf03nq7fcfhpfr5dppr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppHarshRp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZEm9ceSJy87Urljo0jLbjo51kt5wBNn4',
    appId: '1:1047355236192:ios:c80a83f83ba03f3a7fc805',
    messagingSenderId: '1047355236192',
    projectId: 'we-chat-a3450',
    storageBucket: 'we-chat-a3450.appspot.com',
    androidClientId: '1047355236192-sotl8situia81g3ribv9feugl6tn0b1h.apps.googleusercontent.com',
    iosClientId: '1047355236192-87rb0l8034n6hf03nq7fcfhpfr5dppr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppHarshRp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSBOgcphDfB_pbEKLZTsjfB2RiNeR51Rc',
    appId: '1:1047355236192:web:1869e7a377840d667fc805',
    messagingSenderId: '1047355236192',
    projectId: 'we-chat-a3450',
    authDomain: 'we-chat-a3450.firebaseapp.com',
    storageBucket: 'we-chat-a3450.appspot.com',
    measurementId: 'G-8BG919CF9D',
  );

}